"""
kpi_app/kpi.py

Synthetic telecom KPI monitoring application.
This is the TARGET system — the code whose tests are generated by the agent.

Initial state: 3 features (as described in the paper Section 5.1)
  - calculate_cell_availability
  - check_rsrp_signal
  - check_call_drop_rate

Extended state (added to feature branch): 3 new features
  - check_handover_success_rate
  - validate_latency_sla
  - calculate_throughput

This file mirrors the structure described in:
"Context-Aware Generative AI for Automated Telecom Test Script Generation"
Prasad G., Chandramohan T.N., Bose J. — Ericsson R&D Bangalore
"""


# ── Feature 1: Cell Availability ─────────────────────────────────────────────

def calculate_cell_availability(
    total_time_minutes: float,
    downtime_minutes: float
) -> float:
    """
    Calculate cell availability as a percentage.

    Args:
        total_time_minutes: Total observation period in minutes
        downtime_minutes: Total downtime during the period in minutes

    Returns:
        Availability percentage (0.0 to 100.0)

    Raises:
        ValueError: If inputs are invalid
    """
    if total_time_minutes <= 0:
        raise ValueError("total_time_minutes must be positive")
    if downtime_minutes < 0:
        raise ValueError("downtime_minutes must be non-negative")
    if downtime_minutes > total_time_minutes:
        raise ValueError("downtime cannot exceed total time")

    uptime = total_time_minutes - downtime_minutes
    return (uptime / total_time_minutes) * 100.0


# ── Feature 2: RSRP Signal Strength ──────────────────────────────────────────

RSRP_EXCELLENT = -80.0   # dBm — excellent signal
RSRP_GOOD = -90.0        # dBm — good signal
RSRP_FAIR = -100.0       # dBm — fair signal
RSRP_POOR = -110.0       # dBm — poor signal threshold


def check_rsrp_signal(rsrp_dbm: float) -> dict:
    """
    Check whether RSRP (Reference Signal Received Power) is within bounds.

    RSRP is a key LTE/5G signal quality metric measured in dBm.
    Typical range: -44 dBm (excellent) to -140 dBm (no signal).

    Args:
        rsrp_dbm: RSRP value in dBm

    Returns:
        Dict with keys:
            - value: the input RSRP value
            - quality: one of 'excellent', 'good', 'fair', 'poor', 'no_signal'
            - acceptable: bool — True if signal is usable (>= -110 dBm)
            - message: human-readable description
    """
    if rsrp_dbm >= RSRP_EXCELLENT:
        quality = "excellent"
        acceptable = True
        message = "Strong signal — optimal performance expected"
    elif rsrp_dbm >= RSRP_GOOD:
        quality = "good"
        acceptable = True
        message = "Good signal — normal performance expected"
    elif rsrp_dbm >= RSRP_FAIR:
        quality = "fair"
        acceptable = True
        message = "Fair signal — some degradation possible"
    elif rsrp_dbm >= RSRP_POOR:
        quality = "poor"
        acceptable = False
        message = "Poor signal — significant degradation likely"
    else:
        quality = "no_signal"
        acceptable = False
        message = "No usable signal"

    return {
        "value": rsrp_dbm,
        "quality": quality,
        "acceptable": acceptable,
        "message": message,
    }


# ── Feature 3: Call Drop Rate ─────────────────────────────────────────────────

DEFAULT_CALL_DROP_THRESHOLD = 2.0  # percent — 3GPP typical SLA


def check_call_drop_rate(
    dropped_calls: int,
    total_calls: int,
    threshold_percent: float = DEFAULT_CALL_DROP_THRESHOLD,
) -> dict:
    """
    Check whether call drop rate exceeds a configured threshold.

    Args:
        dropped_calls: Number of dropped calls
        total_calls: Total number of calls attempted
        threshold_percent: Maximum acceptable drop rate (default 2.0%)

    Returns:
        Dict with keys:
            - drop_rate: calculated drop rate as percentage
            - threshold: the configured threshold
            - within_sla: True if drop_rate <= threshold
            - message: human-readable status

    Raises:
        ValueError: If inputs are invalid
    """
    if total_calls <= 0:
        raise ValueError("total_calls must be positive")
    if dropped_calls < 0:
        raise ValueError("dropped_calls must be non-negative")
    if dropped_calls > total_calls:
        raise ValueError("dropped_calls cannot exceed total_calls")

    drop_rate = (dropped_calls / total_calls) * 100.0
    within_sla = drop_rate <= threshold_percent

    return {
        "drop_rate": round(drop_rate, 4),
        "threshold": threshold_percent,
        "within_sla": within_sla,
        "message": (
            f"Drop rate {drop_rate:.2f}% is within SLA ({threshold_percent}%)"
            if within_sla
            else f"Drop rate {drop_rate:.2f}% EXCEEDS SLA threshold ({threshold_percent}%)"
        ),
    }


# ── Feature 4: Handover Success Rate (new feature) ───────────────────────────

DEFAULT_HANDOVER_THRESHOLD = 95.0  # percent


def check_handover_success_rate(
    successful_handovers: int,
    total_handovers: int,
    threshold_percent: float = DEFAULT_HANDOVER_THRESHOLD,
) -> dict:
    """
    Check handover success rate against SLA threshold.

    Handover success rate measures how often UEs successfully
    transition between cells without connection loss.

    Args:
        successful_handovers: Number of successful handovers
        total_handovers: Total handover attempts
        threshold_percent: Minimum acceptable success rate (default 95%)

    Returns:
        Dict with keys:
            - success_rate: calculated rate as percentage
            - threshold: the configured threshold
            - within_sla: True if success_rate >= threshold
            - message: human-readable status

    Raises:
        ValueError: If inputs are invalid
    """
    if total_handovers <= 0:
        raise ValueError("total_handovers must be positive")
    if successful_handovers < 0:
        raise ValueError("successful_handovers must be non-negative")
    if successful_handovers > total_handovers:
        raise ValueError("successful_handovers cannot exceed total_handovers")

    success_rate = (successful_handovers / total_handovers) * 100.0
    within_sla = success_rate >= threshold_percent

    return {
        "success_rate": round(success_rate, 4),
        "threshold": threshold_percent,
        "within_sla": within_sla,
        "message": (
            f"Handover success rate {success_rate:.2f}% meets SLA ({threshold_percent}%)"
            if within_sla
            else f"Handover success rate {success_rate:.2f}% BELOW SLA threshold ({threshold_percent}%)"
        ),
    }


# ── Feature 5: Latency SLA Validation (new feature) ──────────────────────────

DEFAULT_LATENCY_THRESHOLD_MS = 100.0  # ms — typical eMBB SLA


def validate_latency_sla(
    measured_latency_ms: float,
    threshold_ms: float = DEFAULT_LATENCY_THRESHOLD_MS,
) -> dict:
    """
    Validate that network latency meets SLA requirements.

    Args:
        measured_latency_ms: Measured end-to-end latency in milliseconds
        threshold_ms: Maximum acceptable latency (default 100ms)

    Returns:
        Dict with keys:
            - latency_ms: the measured latency
            - threshold_ms: the SLA threshold
            - within_sla: True if latency <= threshold
            - margin_ms: how far from the threshold (positive = headroom)
            - message: human-readable status

    Raises:
        ValueError: If latency is negative
    """
    if measured_latency_ms < 0:
        raise ValueError("latency cannot be negative")
    if threshold_ms <= 0:
        raise ValueError("threshold must be positive")

    within_sla = measured_latency_ms <= threshold_ms
    margin_ms = threshold_ms - measured_latency_ms

    return {
        "latency_ms": measured_latency_ms,
        "threshold_ms": threshold_ms,
        "within_sla": within_sla,
        "margin_ms": round(margin_ms, 2),
        "message": (
            f"Latency {measured_latency_ms}ms within SLA ({threshold_ms}ms), "
            f"margin {margin_ms:.1f}ms"
            if within_sla
            else f"Latency {measured_latency_ms}ms EXCEEDS SLA ({threshold_ms}ms) "
            f"by {abs(margin_ms):.1f}ms"
        ),
    }


# ── Feature 6: Network Throughput (new feature) ───────────────────────────────

def calculate_throughput(
    bytes_transferred: int,
    duration_seconds: float,
) -> dict:
    """
    Calculate network throughput in Mbps.

    Args:
        bytes_transferred: Total bytes transferred
        duration_seconds: Measurement window in seconds

    Returns:
        Dict with keys:
            - throughput_mbps: throughput in megabits per second
            - throughput_kbps: throughput in kilobits per second
            - bytes_transferred: the input value
            - duration_seconds: the input value

    Raises:
        ValueError: If inputs are invalid
    """
    if bytes_transferred < 0:
        raise ValueError("bytes_transferred must be non-negative")
    if duration_seconds <= 0:
        raise ValueError("duration_seconds must be positive")

    bits = bytes_transferred * 8
    throughput_bps = bits / duration_seconds
    throughput_kbps = throughput_bps / 1_000
    throughput_mbps = throughput_bps / 1_000_000

    return {
        "throughput_mbps": round(throughput_mbps, 4),
        "throughput_kbps": round(throughput_kbps, 4),
        "bytes_transferred": bytes_transferred,
        "duration_seconds": duration_seconds,
    }
